name: Playwright Tests + Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '30 16 * * *' # 23:30 WIB
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci


      - name: Install Playwright Browsers
        run: |
          npx playwright install chromium
         
      - name: Run Playwright Tests
        run: npm run tests | tee test-log.txt

      - name: Upload Test Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test-log.txt

      - name: Run AI Test Analyzer
        if: always()
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node ai-analyzer.js
     
      - name: Generate Allure Report
        if: always()
        run: |
          ALLURE_VERSION=2.27.0

          wget -q https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip -q -o allure-${ALLURE_VERSION}.zip -d $HOME/.allure

          export PATH=$HOME/.allure/allure-${ALLURE_VERSION}/bin:$PATH

          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30